pm2:
  script: bin/lvyjs.js
  args:
    - dev
    - --alemonjs
    - --login
    - gui
  env:
    NODE_ENV: development
pkg:
  '@alemonjs/kook': ^0.0.3
  '@alemonjs/gui': ^0.0.3
  alemonjs: ^2.0.0-rc.44
kook:
  token: ''
gui:
  port: 9601
