name: 发布版本

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  macos-build:
    runs-on: macos-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 缓存依赖和 Electron Builder 缓存
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache/electron-builder
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: yarn

      - name: 安装依赖
        run: |
          corepack enable
          rm -rf .npmrc
          yarn install --ignore-engines

      - name: 构建 macOS 应用
        run: |
          yarn build-resources
          npx electron-builder -c electron-builder.cjs --mac --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 缓存依赖和 Electron Builder 缓存
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache/electron-builder
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: yarn

      - name: 安装依赖
        run: |
          corepack enable
          rm -rf .npmrc
          yarn install --ignore-engines

      - name: 构建 Linux 应用
        run: |
          yarn build-resources
          npx electron-builder -c electron-builder.cjs --linux --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows-build:
    runs-on: windows-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 缓存依赖和 Electron Builder 缓存
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache/electron-builder
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: yarn

      - name: 安装依赖
        run: |
          corepack enable
          rm -rf .npmrc
          yarn install --ignore-engines

      - name: 构建 Windows 应用
        run: |
          yarn build-resources
          npx electron-builder -c electron-builder.cjs --win --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
