name: 开发分支

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-dev-branch:
    runs-on: macos-latest

    steps:
      - name: 检出代码库
        uses: actions/checkout@v2

      - name: 根据时间戳生成分支名称
        id: generate-branch
        run: |
          DATE=$(date -u +'%Y%m%d')
          TIMESTAMP=$(date +%s)
          BRANCH_NAME="dev-$DATE-$TIMESTAMP"
          echo "Generated branch name: $BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: 创建新分支
        run: |
          NEW_BRANCH=${{ steps.generate-branch.outputs.branch_name }}
          echo "Creating branch: $NEW_BRANCH"
          git checkout -b $NEW_BRANCH
          git push origin $NEW_BRANCH
